### ISSUE TITLE
Unable to pick one of multiple VSI images.

### ISSUE THREAD

**Issue by tnakaike** [ibm-hyper-protect/linuxone-vsi-automation-samples#32]
The current code to find an available VSI image is

`hyper_protect_image = one(toset([for each in data.ibm_is_images.hyper_protect_images.images : each if each.os == "hyper-protect-1-0-s390x" && each.architecture == "s390x"]))
`

This works only when the avaiable images is one because the `one` function does not work for the set that has more than one element.

We need a solution to select the latest version based on semantic versioning.

#31 is a workaround to avoid the above error for the meantime.

**Comment by CarstenLeue** [comment]
This has been addressed by https://github.com/ibm-hyper-protect/terraform-provider-hpcr/pull/12
